version: '3.7'

services:
    api:
        build: .
        ports:
        - "80:3001"
    # mongodb:
    #     image: mongo:latest
    #     container_name: mongodb
    #     restart: always
    #     environment:
    #         MONGO_INITDB_ROOT_USERNAME: lotteryapp
    #         MONGO_INITDB_ROOT_PASSWORD: lotteryapp
    #         MONGO_INITDB_DATABASE: lotteryapp
    #     ports:
    #         - 27018:27017
    #     volumes:
    #         - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro